name: David Obatake
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
